### PR TITLE
Further out of tree build fixes

### PR DESCRIPTION
**Pull request by schnitzeltony**
They slipped me through somehow...

### CODE REVIEW

**Comment by beanpole135** [comment]
This pull request has conflicts with the master branch.
Please resolve these conflicts on your personal branch and commit the changes, then the pull request should automatically update so I can review/merge the changes.

**Comment by schnitzeltony** [comment]
rebased & build tested

**Comment by beanpole135** [comment]
Thanks for making those changes!

**Comment by schnitzeltony** [comment]
Thanks for making this project :)

**Pull request merged**
